sudo: false
language: python
python:
  - "2.7"
  - "3"
virtualenv:
  system_site_packages: false
env:
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="2.7" COVERAGE="true"
    - DISTRIB="conda" PYTHON_VERSION="3.6" COVERAGE="true"
# command to install dependencies
install: source ci/install.sh
# command to run tests
script: nosetests -sv --with-doctest --no-byte-compile --with-coverage --cover-package=pyhht
after_success:
  coveralls
